#!/usr/bin/env bash
# Run from top level directory of package
source ./continuous_integration/setup_env.sh
# Function to read off store
store_info()
{
	# Store a record of what's in the cached tarball
	# This record allows us to automatically regenerate the tarball if the
	# installed packages change.
	rm -f "$1"
	cat > "$1" <<-EOT
		# -- cache information; autogenerated by ci/install.sh
		MINICONDA_VERSION=$MINICONDA_VERSION
		CHANNEL=$CHANNEL
		PACKAGES=$PACKAGES
EOT
	cat "$1"
}
store_info "${store_dir}/info.txt"
if [[ -f "$CACHE_TARBALL_PATH" ]] && cmp "${store_dir}/info.txt" "$CACHE_DIR/info.txt"; then
	#
	# Restore from cached tarball
	#
        tar xzf "$CACHE_TARBALL_PATH" -C "${store_dir}" 
	ls -l "${store_dir}"
else
    ./continuous_integration/install_miniconda.sh
    ./continuous_integration/conda_install_dep.sh
    ./continuous_integration/cleanup.sh
fi
